### PR TITLE
(feat): Add all boolean pipes and their respective tests

### PR DESCRIPTION
**Pull request by rafaelss95**
I added all boolean pipes that I saw in [**angular-filter**](https://github.com/a8m/angular-filter/blob/master/test/spec/filter/boolean/conditions.js). By the way, I took the liberty of divide those pipes in separated files, because (at least for me) it provides a better readability and facilitates the maintenance. I hope it's ok.

Also, I renamed some test files to follow the good practices that are in  [**Angular - style guide**](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-10). Basically I changed the order of suffixes on files.

Do you have plans to add [**those pipes**](https://github.com/a8m/angular-filter/blob/master/src/_filter/boolean/angular.js) also?

### CODE REVIEW

**Comment by a8m** [comment]
Looks good @rafaelss95 

> Do you have plans to add those pipes also?

Yes, would you mind to help with that?  :)

**Comment by rafaelss95** [comment]
@a8m It's done :)

**Comment by a8m** [comment]
Awesome @rafaelss95 !

Just note that you need to [set your email in git](https://help.github.com/articles/setting-your-email-in-git/) and then your contribution will show up.

**Comment by rafaelss95** [comment]
@a8m I just forgot this. I think it's everything fine now. :)

**Pull request merged**
